apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: monitoring
spec:
  secretName: grafana
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - dev.dashboard.your.site

