---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: your_cloud-apps 
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-deploy-authentication
  url: git@your_repos.git/kube-deploy

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: owncloud-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./owncloud-manifests
  prune: true
  dependsOn:
    - name: helpmanager
  sourceRef:
    kind: GitRepository
    name: your_cloud-apps
    namespace: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: seeddms-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./seeddms-manifests
  prune: true
  dependsOn:
    - name: helpmanager
  sourceRef:
    kind: GitRepository
    name: your_cloud-apps
    namespace: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: suitecrm-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./suitecrm-manifests
  prune: true
  dependsOn:
    - name: helpmanager
  sourceRef:
    kind: GitRepository
    name: your_cloud-apps
    namespace: flux-system

