apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: monacocloud-configs
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://your_repos/k8s
  secretRef:
    name: flux-system
  ref:
    branch: main
  ignore: |
    flux/**

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certmanager
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infra-deploy/certmanager
  prune: true
  sourceRef:
    kind: GitRepository
    name: monacocloud-configs

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infra-deploy/traefik
  prune: true
  dependsOn:
    - name: certmanager
  sourceRef:
    kind: GitRepository
    name: monacocloud-configs

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infra-deploy/prometheus
  prune: true
  dependsOn:
    - name: traefik
  sourceRef:
    kind: GitRepository
    name: monacocloud-configs

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-manager
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infra-deploy/app-manager
  prune: true
  dependsOn:
    - name: prometheus
  sourceRef:
    kind: GitRepository
    name: monacocloud-configs
